// AUTO-GENERATED by generateFieldMap.mjs
// Edit per-field properties here (width/fontSize/etc)

export type Direction = "auto" | "ltr" | "rtl";

export type FieldSpec = {
  pageIndex: number;
  x: number;
  y: number;

  // existing:
  width?: number;
  height?: number;
  fontSize?: number;
  lineHeight?: number;
  align?: "left" | "center" | "right";
  direction?: "ltr" | "rtl" | "auto";
  clearBackground?: boolean;

  // ✅ new:
  kind?: "text" | "checkbox";
  boxSize?: number;      // size of the X for checkbox
  strokeWidth?: number;  // thickness of the X
};

export type FieldMap = Record<string, FieldSpec>;

export const fieldMap: FieldMap = {
  "firstNameHebrew": { pageIndex: 0, x: 447.1, y: 625.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "firstNameEnglish": { pageIndex: 0, x: 451.1, y: 590.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "lastNameHebrew": { pageIndex: 0, x: 492.1, y: 626.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "lastNameEnglish": { pageIndex: 0, x: 488.1, y: 590.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "prevLastNameHebrew": { pageIndex: 0, x: 220.1, y: 590.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "prevLastNameEnglish": { pageIndex: 0, x: 305.1, y: 591.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "prevFirstNameHebrew": { pageIndex: 0, x: 271.1, y: 627.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "birthDate": { pageIndex: 0, x: 129.2, y: 595.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "birthCountry": { pageIndex: 0, x: 526.75, y: 526.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "birthCity": { pageIndex: 0, x: 453.75, y: 529.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "citizenship": { pageIndex: 0, x: 336.75, y: 564.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "passportNumber": { pageIndex: 0, x: 288.75, y: 525.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "passportIssuanceCountry": { pageIndex: 0, x: 268.75, y: 528.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "passportIssueDate": { pageIndex: 0, x: 127.2, y: 522.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "passportExpiryDate": { pageIndex: 0, x: 42.2, y: 523.72, direction: "ltr", fontSize: 12, clearBackground: false },
  "visaStartDate": { pageIndex: 0, x: 468.75, y: 441.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "visaEndDate": { pageIndex: 0, x: 381.75, y: 441.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "visaDateOfArrival": { pageIndex: 0, x: 41.2, y: 439.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "address.street": { pageIndex: 0, x: 520.75, y: 373.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "address.homeNumber": { pageIndex: 0, x: 403.75, y: 376.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "address.entrance": { pageIndex: 0, x: 381.75, y: 375.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "address.apartmentNumber": { pageIndex: 0, x: 267.1, y: 374.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "address.city": { pageIndex: 0, x: 240.1, y: 375.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "address.zipcode": { pageIndex: 0, x: 119.1, y: 375.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "address.phoneNumber": { pageIndex: 0, x: 46.1, y: 375.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "fatherLastNameHebrew": { pageIndex: 0, x: 533.75, y: 228.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "fatherLastNameEnglish": { pageIndex: 0, x: 532.75, y: 178.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "fatherFirstNameEnglish": { pageIndex: 0, x: 428.75, y: 178.72, direction: "ltr", fontSize: 12, clearBackground: false },
  "fatherFirstNameHebrew": { pageIndex: 0, x: 468.75, y: 228.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "fatherIdNumber": { pageIndex: 0, x: 301.75, y: 218.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "fatherPassportNumber": { pageIndex: 0, x: 301.75, y: 197.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "motherLastNameHebrew": { pageIndex: 0, x: 281.75, y: 227.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "motherLastNameEnglish": { pageIndex: 0, x: 235.75, y: 180.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "motherFirstNameHebrew": { pageIndex: 0, x: 213.75, y: 228.72, direction: "rtl", fontSize: 12, clearBackground: false },
  "motherFirstNameEnglish": { pageIndex: 0, x: 171.75, y: 179.72, direction: "ltr", fontSize: 12, clearBackground: false },
  "motherIdNumber": { pageIndex: 0, x: 45.2, y: 219.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "motherPassportNumber": { pageIndex: 0, x: 46.2, y: 196.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "maritalStatusLastUpdateDate": { pageIndex: 0, x: 389.75, y: 123.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "numberChildrenUnder18": { pageIndex: 0, x: 399.75, y: 71.72, direction: "ltr", fontSize: 12, clearBackground: false },
  "partnerLastNameHebrew": { pageIndex: 0, x: 303.75, y: 110.72, direction: "rtl", fontSize: 12, clearBackground: false },
  "partnerLastNameEnglish": { pageIndex: 0, x: 268.75, y: 75.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "partnerFirstNameHebrew": { pageIndex: 0, x: 234.2, y: 111.72, direction: "rtl", fontSize: 12, clearBackground: false },
  "partnerFirstNameEnglish": { pageIndex: 0, x: 193.2, y: 74.72, direction: "ltr", fontSize: 12, clearBackground: false },
  "partnerIdNumber": { pageIndex: 0, x: 47.2, y: 101.72, direction: "ltr", fontSize: 12, clearBackground: false },
  "partnerPassportNumber": { pageIndex: 0, x: 46.2, y: 79.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "purposeOfStay": { pageIndex: 1, x: 399.2, y: 748.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "bankName": { pageIndex: 1, x: 490.75, y: 615.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "bankBranch": { pageIndex: 1, x: 337.75, y: 615.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "bankAccountNumber": { pageIndex: 1, x: 70.55, y: 615.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "employerName": { pageIndex: 1, x: 332.55, y: 530.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "employerAddress": { pageIndex: 1, x: 147.55, y: 528.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "selfEmploymentStartDate": { pageIndex: 1, x: 273.85, y: 495.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "unemployedWithIncomeStartDate": { pageIndex: 1, x: 274.85, y: 464.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "selfEmployedYearlyIncome": { pageIndex: 1, x: 83.2, y: 497.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "unemployedYearlyIncome": { pageIndex: 1, x: 83.2, y: 469.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "nationalInsuranceFileNumber": { pageIndex: 1, x: 276.75, y: 384.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad1StartDate": { pageIndex: 1, x: 439.75, y: 310.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad2StartDate": { pageIndex: 1, x: 440.75, y: 289.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad3StartDate": { pageIndex: 1, x: 439.75, y: 270.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad1EndDate": { pageIndex: 1, x: 335.75, y: 311.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad2EndDate": { pageIndex: 1, x: 335.75, y: 288.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad3EndDate": { pageIndex: 1, x: 335.75, y: 268.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad1Purpose": { pageIndex: 1, x: 307.75, y: 310.42, direction: "ltr", fontSize: 12, clearBackground: false },
  "tripAbroad2Purpose": { pageIndex: 1, x: 308.75, y: 289.42, direction: "rtl", fontSize: 12, clearBackground: false },
  "tripAbroad3Purpose": { pageIndex: 1, x: 309.75, y: 268.72, direction: "rtl", fontSize: 12, clearBackground: false },
  "NationInsuranceTypeOfAllowance": { pageIndex: 1, x: 332.2, y: 183.72, direction: "rtl", fontSize: 12, clearBackground: false },
  "NationInsuranceFileNumber": { pageIndex: 1, x: 173.2, y: 171.42, direction: "ltr", fontSize: 12, clearBackground: false }
};
