// AUTO-GENERATED by generateFieldMap.mjs
// Edit per-field properties here (width/fontSize/etc)

export type Direction = "auto" | "ltr" | "rtl";

export type FieldSpec = {
  pageIndex: number;
  x: number;
  y: number;

  // existing:
  width?: number;
  height?: number;
  fontSize?: number;
  lineHeight?: number;
  align?: "left" | "center" | "right";
  direction?: "ltr" | "rtl" | "auto";
  clearBackground?: boolean;

  // ✅ new:
  kind?: "text" | "checkbox" | "signature";
  boxSize?: number; // size of the X for checkbox
  strokeWidth?: number; // thickness of the X
};
export type FieldMap = Record<string, FieldSpec>;

export const fieldMap: FieldMap = {
  "children.child1.dateOfBirth": {
    pageIndex: 0,
    x: 262.56,
    y: 185.15,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child1.firstName": {
    pageIndex: 0,
    x: 450.79,
    y: 183.92,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child1.placeOfBirth": {
    pageIndex: 0,
    x: 150.31,
    y: 185.15,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child2.dateOfBirth": {
    pageIndex: 0,
    x: 262.79,
    y: 157.87,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child2.firstName": {
    pageIndex: 0,
    x: 450.79,
    y: 159.31,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child2.placeOfBirth": {
    pageIndex: 0,
    x: 150.08,
    y: 159.41,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child3.dateOfBirth": {
    pageIndex: 0,
    x: 262.79,
    y: 134.69,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child3.firstName": {
    pageIndex: 0,
    x: 450.79,
    y: 136.03,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "children.child3.placeOfBirth": {
    pageIndex: 0,
    x: 150.85,
    y: 136.23,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "foreignParent.firstName": {
    pageIndex: 0,
    x: 400.41,
    y: 324.18,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "foreignParent.idOrPassportNumber": {
    pageIndex: 0,
    x: 275.1,
    y: 271.1,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "foreignParent.lastName": {
    pageIndex: 0,
    x: 375.33,
    y: 298.79,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  formDate: {
    pageIndex: 0,
    x: 58.92,
    y: 700.79,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.address": {
    pageIndex: 0,
    x: 330.41,
    y: 567.36,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.firstName": {
    pageIndex: 0,
    x: 375.56,
    y: 640.33,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.idNumber": {
    pageIndex: 0,
    x: 350.95,
    y: 590.03,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.lastName": {
    pageIndex: 0,
    x: 375.26,
    y: 615.72,
    direction: "rtl",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.phoneMobile": {
    pageIndex: 0,
    x: 320.26,
    y: 546.03,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.poBox": {
    pageIndex: 0,
    x: 60.85,
    y: 545.03,
    direction: "ltr",
    fontSize: 12,
    clearBackground: false,
  },
  "israeliApplicant.maritalStatus.married": {
    pageIndex: 0,
    x: 556.4,
    y: 421.7,
    kind: "checkbox",
    boxSize: 5,
    strokeWidth: 1.2,
  },
  "israeliApplicant.maritalStatus.divorced": {
    pageIndex: 0,
    x: 466.2,
    y: 421.7,
    kind: "checkbox",
    boxSize: 5,
    strokeWidth: 1.2,
  },
  "israeliApplicant.maritalStatus.widowed": {
    pageIndex: 0,
    x: 374.1,
    y: 421.7,
    kind: "checkbox",
    boxSize: 5,
    strokeWidth: 1.2,
  },
  "israeliApplicant.maritalStatus.single": {
    pageIndex: 0,
    x: 287.9,
    y: 421.7,
    kind: "checkbox",
    boxSize: 5,
    strokeWidth: 1.2,
  },
  "israeliApplicant.maritalStatus.bigamist": {
    pageIndex: 0,
    x: 190.0,
    y: 421.7,
    kind: "checkbox",
    boxSize: 5,
    strokeWidth: 1.2,
  },
  applicantSignature: {
    pageIndex: 0,
    x: 30,
    y: 115,
    // height: 500,
    width: 100, // bigger
    height: 30, // bigger
    kind: "signature",
    direction: "auto",
    clearBackground: false,
  },
};
