// AUTO-GENERATED by generateFieldMap.mjs
// Edit per-field properties here (width/fontSize/etc)

export type Direction = "auto" | "ltr" | "rtl";

export type FieldSpec = {
  pageIndex: number;
  x: number;
  y: number;
  direction?: Direction;
  width?: number;
  height?: number;
  fontSize?: number;
  lineHeight?: number;
  align?: "left" | "center" | "right";
  maxFontSize?: number;
  minFontSize?: number;
  clearBackground?: boolean;
};

export type FieldMap = Record<string, FieldSpec>;

export const fieldMap: FieldMap = {
  "children.child1.dateOfBirth": { pageIndex: 0, x: 262.56, y: 185.15, direction: "ltr", fontSize: 12, clearBackground: false },
  "children.child1.firstName": { pageIndex: 0, x: 541.79, y: 183.92, direction: "ltr", fontSize: 12, clearBackground: false },
  "children.child1.placeOfBirth": { pageIndex: 0, x: 214.31, y: 185.15, direction: "rtl", fontSize: 12, clearBackground: false },
  "children.child2.dateOfBirth": { pageIndex: 0, x: 261.79, y: 157.87, direction: "ltr", fontSize: 12, clearBackground: false },
  "children.child2.firstName": { pageIndex: 0, x: 541.79, y: 159.31, direction: "rtl", fontSize: 12, clearBackground: false },
  "children.child2.placeOfBirth": { pageIndex: 0, x: 215.08, y: 159.41, direction: "rtl", fontSize: 12, clearBackground: false },
  "children.child3.dateOfBirth": { pageIndex: 0, x: 261.79, y: 134.69, direction: "ltr", fontSize: 12, clearBackground: false },
  "children.child3.firstName": { pageIndex: 0, x: 541.79, y: 136.03, direction: "rtl", fontSize: 12, clearBackground: false },
  "children.child3.placeOfBirth": { pageIndex: 0, x: 215.85, y: 136.23, direction: "ltr", fontSize: 12, clearBackground: false },
  "foreignParent.firstName": { pageIndex: 0, x: 436.41, y: 324.18, direction: "rtl", fontSize: 12, clearBackground: false },
  "foreignParent.idOrPassportNumber": { pageIndex: 0, x: 244.1, y: 271.1, direction: "ltr", fontSize: 12, clearBackground: false },
  "foreignParent.lastName": { pageIndex: 0, x: 443.33, y: 298.79, direction: "rtl", fontSize: 12, clearBackground: false },
  "formDate": { pageIndex: 0, x: 58.92, y: 700.79, direction: "ltr", fontSize: 12, clearBackground: false },
  "israeliApplicant.address": { pageIndex: 0, x: 442.41, y: 571.36, direction: "rtl", fontSize: 12, clearBackground: false },
  "israeliApplicant.firstName": { pageIndex: 0, x: 408.56, y: 640.33, direction: "rtl", fontSize: 12, clearBackground: false },
  "israeliApplicant.idNumber": { pageIndex: 0, x: 313.95, y: 594.03, direction: "ltr", fontSize: 12, clearBackground: false },
  "israeliApplicant.lastName": { pageIndex: 0, x: 426.26, y: 615.72, direction: "rtl", fontSize: 12, clearBackground: false },
  "israeliApplicant.phoneMobile": { pageIndex: 0, x: 286.26, y: 546.03, direction: "ltr", fontSize: 12, clearBackground: false },
};
